version: 2.1

orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.2

jobs:
  build:
    # Compile typescript ??
  test:
    # Test typescript

  deploy-dev:
    # Deploy to one environment

  deploy-prod:
  # When release tag is added
  # Some type of manual step ???


workflows:
  test-and-deploy:
      jobs:
        - node/test
        - heroku/deploy-via-git:
            filters:
              branches:
                only:
                  - master
            requires:
              - node/test