version: 2.1

orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.2

workflows:  
  build-test-deploy:
    jobs:
      - node/test
      - heroku/deploy-via-git:
          app-name: $HEROKU_API_DEV_ENV
          requires:
            - node/test
          filters:
            branches:
              only:
              - main
            tags:
              ignore: /.*/
      - hold-for-prod:
          type: approval
          requires:
            - node/test
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - main
      - heroku/deploy-via-git:
          app-name: $HEROKU_API_PROD_ENV
          requires:
            - hold-for-prod
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - main


