version: 2.1

orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@1.2.2

workflows:  
  version: 2
  build-test-deploy:
    jobs:
      - node/test:
          filters:
            tags:
              only: /^v.*/

      - heroku/deploy-via-git:
          name: deploy-dev-app
          app-name: $HEROKU_API_DEV_ENV
          requires:
            - node/test
          filters:
            branches:
              only:
              - main

      - hold-for-prod:
          type: approval
          requires:
            - node/test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - heroku/deploy-via-git:
          name: deploy-prod-app
          app-name: $HEROKU_API_PROD_ENV
          requires:
            - hold-for-prod
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
